import React from "react";
import Head from "next/head";
import styles from "@/styles/dashboard.css";


export default class Dashboard extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container">
          <h1>Olimjon</h1>
          <p>27.03.2025</p>
        </div>
      </>
    );
  }
}
